Add a check for missing DLLs for Windows builds in GitHub Actions

diff --git a/.github/workflows/autobuild.yml b/.github/workflows/autobuild.yml
--- a/.github/workflows/autobuild.yml
+++ b/.github/workflows/autobuild.yml
@@ -72,6 +72,31 @@ jobs:
           cp -r ../../scripts .
           cp ../../assets/LICENSE.mkxp-z-with-https.txt .
 
+      - name: Check for DLLs missing from the artifact
+        shell: msys2 {0}
+        run: |
+          cd build/artifact
+          ldd_output="$(ldd mkxp-z.exe)"
+          echo "$ldd_output"
+
+          error_flag=
+
+          while IFS= read -r line
+          do
+            dll_name="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 1 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
+            dll_location="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 2 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
+            if [[ "$dll_location" = 'not found'* ]] || [[ "$dll_location" = '/mingw64/bin/'* ]] || [[ "$dll_location" = '/mingw64/lib/'* ]] || [[ "$dll_location" = '/mingw64/usr/bin/'* ]] || [[ "$dll_location" = '/mingw64/usr/lib/'* ]]
+            then
+              error_flag=1
+              echo "::error::$dll_name is missing from the artifact"
+            fi
+          done <<< "$ldd_output"
+
+          if [ -n "$error_flag" ]
+          then
+            exit 1
+          fi
+
       - uses: actions/upload-artifact@v4
         with:
           name: mkxp-z.windows.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
